### ISSUE TITLE
Data preprocessing for help

### ISSUE THREAD

**Issue by Pang-b0** [MjdMahasneh/AttentNet#1]
Hello, I read your article and am very interested in the content. I hope I can reproduce your code. I want to know if you can provide the results of data preprocessing. Thank you very much.

**Comment by MjdMahasneh** [comment]
Thank you for your interest, unfortunately I don't have access to the results now.

**Comment by Pang-b0** [comment]
> 感谢您的关注，很遗憾我现在无法访问结果。

Can you provide a. py file for data preprocessing?
